// src/main.rs
use clap::{Args, Parser, Subcommand};

use datapostproc_rust::data::H5File;
use datapostproc_rust::hdf5::{Block, BlockValue, H5Data};
use datapostproc_rust::math::avg::avg_to_profile;
use datapostproc_rust::math::fik::{
    fik_average, fik_decomposition, fik_decomposition_planes, FikDecomposition,
};
use datapostproc_rust::math::rd::{rd_decomposition, RdDecomposition};
use datapostproc_rust::math::spectrum::SpanwiseSpectrum;
use datapostproc_rust::math::tke::{tke_fields, TkeFields};
use datapostproc_rust::math::vortex::vortex_criteria;
use datapostproc_rust::math::wall::{friction_velocity, wall_shear_stress};
use datapostproc_rust::output::dat::write_dat;
use datapostproc_rust::output::normalize::Profiles;
use datapostproc_rust::output::xdmf::{write_xdmf, VarSpec};

use ndarray::{s, Array1, ArrayD, Axis, Ix1};
use std::collections::HashMap;
use std::path::Path;

// ─── CLI definition ───────────────────────────────────────────────────────────

#[derive(Parser)]
#[command(name = "datapostproc", about = "DNS data post-processor")]
struct Cli {
    #[command(subcommand)]
    command: Command,
}

#[derive(Subcommand)]
enum Command {
    /// Average and write statistics to a .dat file.
    Output(OutputArgs),
    /// Generate an XDMF file for Paraview.
    Hdfview(HdfviewArgs),
    /// Spanwise energy spectra and two-point correlations from
    /// instantaneous snapshots.
    Spectra(SpectraArgs),
    /// FIK skin-friction decomposition from a subavg HDF5 file.
    Fik(FikArgs),
    /// FIK skin-friction decomposition from instantaneous snapshots: the
    /// Reynolds stresses are formed on the fly from the fluctuations
    /// (u'u' = ⟨u²⟩ − ū², etc.) with span + ensemble averaging.
    FikInst(FikInstArgs),
    /// Renard–Deck (energy-budget) skin-friction decomposition from a
    /// subavg HDF5 file.
    Rd(RdArgs),
    /// Renard–Deck decomposition from instantaneous snapshots (Reynolds
    /// stresses formed on the fly, like `fik-inst`).
    RdInst(RdInstArgs),
    /// Reynolds-stress components (u'u', v'v', w'w', u'v', u'w', v'w') and
    /// TKE profiles from a subavg HDF5 file.
    Tke(TkeArgs),
    /// Reynolds-stress components and TKE profiles from instantaneous
    /// snapshots (fluctuation moments formed on the fly, like `fik-inst`).
    TkeInst(TkeInstArgs),
    /// Q and λ₂ vortex-identification fields from instantaneous snapshots,
    /// written to an HDF5 file (use `hdfview` to make an XDMF for Paraview).
    Vortex(VortexArgs),
}

/// Hyperslab [start stride count block] for output (4 values, HDF5 convention).
#[derive(Args, Clone)]
struct BlockArgs {
    /// x-direction hyperslab: start stride count block
    #[arg(short = 'x', long, num_args = 4, value_name = "INT")]
    blockx: Option<Vec<usize>>,
    /// y-direction hyperslab: start stride count block
    #[arg(short = 'y', long, num_args = 4, value_name = "INT")]
    blocky: Option<Vec<usize>>,
    /// z-direction hyperslab: start stride count block
    #[arg(short = 'z', long, num_args = 4, value_name = "INT")]
    blockz: Option<Vec<usize>>,
}

/// Hyperslab [start stride count] for hdfview (3 values, XDMF convention).
#[derive(Args, Clone)]
struct ViewBlockArgs {
    /// x-direction hyperslab: start stride count
    #[arg(short = 'x', long, num_args = 3, value_name = "INT")]
    blockx: Option<Vec<usize>>,
    /// y-direction hyperslab: start stride count
    #[arg(short = 'y', long, num_args = 3, value_name = "INT")]
    blocky: Option<Vec<usize>>,
    /// z-direction hyperslab: start stride count
    #[arg(short = 'z', long, num_args = 3, value_name = "INT")]
    blockz: Option<Vec<usize>>,
}

#[derive(Args)]
struct OutputArgs {
    /// Input HDF5 file.
    #[arg(short, long, value_name = "FILE")]
    file: String,
    /// Output .dat file (default: output.dat).
    #[arg(short, long, value_name = "FILE")]
    output: Option<String>,
    /// Variables to process.
    #[arg(short, long, num_args = 1.., value_name = "VAR")]
    variables: Vec<String>,
    /// Wall-normal direction: x, y, or z.
    #[arg(short, long, value_name = "DIR")]
    dire: String,
    /// Normalize to wall units (u+, z+, …).
    #[arg(short, long, default_value_t = false)]
    normalize: bool,
    /// Separate file containing u for computing uτ (default: same as --file).
    #[arg(long, value_name = "FILE")]
    uout: Option<String>,
    #[command(flatten)]
    block: BlockArgs,
}

#[derive(Args)]
struct HdfviewArgs {
    /// Input HDF5 file.
    #[arg(short, long, value_name = "FILE")]
    file: String,
    /// Output .xdmf file (default: same stem as input).
    #[arg(short, long, value_name = "FILE")]
    output: Option<String>,
    /// Variables to include.
    #[arg(short, long, num_args = 1.., value_name = "VAR")]
    variables: Vec<String>,
    #[command(flatten)]
    block: ViewBlockArgs,
}

#[derive(Args)]
struct SpectraArgs {
    /// Instantaneous snapshot HDF5 files; all these plus any generated by
    /// --pattern/--range are ensemble-averaged together.
    #[arg(short, long, num_args = 1.., value_name = "FILE")]
    files: Vec<String>,
    /// Filename pattern with a time placeholder `{t}`, e.g. `inst_{t}_u.h5`.
    /// Expanded over --range into a snapshot series so you don't have to list
    /// every timestep.
    #[arg(long, value_name = "PATTERN")]
    pattern: Option<String>,
    /// Timestep range START END STEP (inclusive) used with --pattern, e.g.
    /// `--range 400000 900000 50000` for 11 snapshots.
    #[arg(long, num_args = 3, value_names = ["START", "END", "STEP"])]
    range: Option<Vec<usize>>,
    /// Dataset name to analyse (u, v, w, p, …).
    #[arg(short, long, default_value = "u")]
    variable: String,
    /// Output stem: writes <stem>_spec.dat and <stem>_corr.dat.
    #[arg(short, long, default_value = "spectra")]
    output: String,
    /// x-index range START END (0-based, half-open, indices of the x
    /// coordinate array) to average over; default: full streamwise extent.
    #[arg(long, num_args = 2, value_name = "INT")]
    xrange: Option<Vec<usize>>,
    /// Wall-normal locations (physical z, wall at 0) written as columns;
    /// each is snapped to the nearest grid point.
    #[arg(long, value_delimiter = ',', default_value = "0.05,0.1,0.2,0.5,1.0")]
    zloc: Vec<f64>,
}

// ─── Entry point ──────────────────────────────────────────────────────────────

fn main() {
    let cli = Cli::parse();
    match cli.command {
        Command::Output(args) => run_output(args),
        Command::Hdfview(args) => run_hdfview(args),
        Command::Spectra(args) => run_spectra(args),
        Command::Fik(args) => run_fik(args),
        Command::FikInst(args) => run_fik_inst(args),
        Command::Rd(args) => run_rd(args),
        Command::RdInst(args) => run_rd_inst(args),
        Command::Tke(args) => run_tke(args),
        Command::TkeInst(args) => run_tke_inst(args),
        Command::Vortex(args) => run_vortex(args),
    }
}

// ─── output sub-command ───────────────────────────────────────────────────────

fn run_output(args: OutputArgs) {
    // Wall-normal axis index (DNS layout: dim-0 = z, dim-1 = y, dim-2 = x)
    let wall_axis = dire_to_axis(&args.dire);

    // Optionally build a Block for hyperslab reading
    let block = build_block(&args.block);

    // Open and initialise the HDF5 file
    let var_refs: Vec<&str> = args.variables.iter().map(String::as_str).collect();
    let mut h5 = H5File::new(&args.file).expect("Failed to open HDF5 file");
    h5.init(&var_refs).expect("Failed to initialise H5File");

    // ── Average each variable to a 1-D wall-normal profile ───────────────────
    let mut profiles: HashMap<String, Array1<f64>> = HashMap::new();

    for var in &args.variables {
        let arr = {
            let data = h5.dataset(var)
                .unwrap_or_else(|| panic!("Variable '{}' not found", var));
            match data.read_data::<f64>().expect("read failed") {
                H5Data::Array(a) => a,
                H5Data::Scalar(_) => panic!("'{}' is a scalar – cannot average", var),
            }
        };
        let profile = avg_to_profile(&arr, wall_axis)
            .expect("averaging failed")
            .into_dimensionality::<Ix1>()
            .expect("dimension error");
        profiles.insert(var.clone(), profile);
    }

    // ── Wall-normal coordinate ────────────────────────────────────────────────
    let coord_arr: Array1<f64> = {
        let data = h5.coord(&args.dire)
            .unwrap_or_else(|| panic!("Coordinate '{}' not found", args.dire));
        match data.read_data::<f64>().expect("coord read failed") {
            H5Data::Array(a) => a.into_dimensionality::<Ix1>().expect("dim error"),
            H5Data::Scalar(_) => panic!("Coordinate '{}' is scalar", args.dire),
        }
    };
    profiles.insert(args.dire.clone(), coord_arr.clone());

    // ── Read u for τ_w computation ────────────────────────────────────────────
    let nu = h5.info().nu.expect("'nu' not found in HDF5 file");

    let u_profile: Array1<f64> = if profiles.contains_key("u") {
        profiles["u"].clone()
    } else {
        // u not in the variable list – load it separately
        let u_path = args.uout.as_deref().unwrap_or(&args.file);
        let mut u_h5 = H5File::new(u_path).expect("Failed to open u file");
        u_h5.add_dataset("u", block.clone()).expect("Cannot open 'u' dataset");
        let arr = {
            let data = u_h5.dataset("u").expect("'u' not found");
            match data.read_data::<f64>().expect("read u failed") {
                H5Data::Array(a) => a,
                H5Data::Scalar(_) => panic!("'u' is scalar"),
            }
        };
        avg_to_profile(&arr, wall_axis)
            .expect("avg u failed")
            .into_dimensionality::<Ix1>()
            .expect("dim error")
    };

    let tau = wall_shear_stress(
        &u_profile.clone().into_dyn(),
        &coord_arr.clone().into_dyn(),
        nu,
    ).expect("τ_w computation failed");
    let utau = friction_velocity(tau);
    // In non-dimensional DNS: Re_τ = uτ / ν
    let ret = utau / nu;

    // ── Optional normalization ────────────────────────────────────────────────
    let final_profiles = if args.normalize {
        let p = Profiles::new(&args.dire, nu, tau, profiles)
            .expect("Profiles::new failed");
        p.to_wall_units().expect("normalization failed")
    } else {
        profiles
    };

    // ── Write .dat ────────────────────────────────────────────────────────────
    let output_path = args.output.unwrap_or_else(|| "output".to_string());
    write_dat(Path::new(&output_path), &args.dire, ret, &final_profiles)
        .expect("Failed to write .dat file");
}

// ─── hdfview sub-command ──────────────────────────────────────────────────────

fn run_hdfview(args: HdfviewArgs) {
    let var_refs: Vec<&str> = args.variables.iter().map(String::as_str).collect();

    let mut h5 = H5File::new(&args.file).expect("Failed to open HDF5 file");
    h5.get_info().expect("Failed to read DNS info");
    h5.load_coords().expect("Failed to load coordinates");
    for v in &var_refs {
        h5.add_dataset(v, None)
            .unwrap_or_else(|_| eprintln!("Warning: dataset '{}' not found, skipping", v));
    }

    let info = h5.info();
    let sx = info.nx.expect("nx not available") as usize;
    let sy = info.ny.expect("ny not available") as usize;
    let sz = info.nz.expect("nz not available") as usize;

    // Find coordinate names actually present in the file
    let varx = find_coord(&h5, 'x').expect("x coordinate not found (tried 'x', 'xc')");
    let vary = find_coord(&h5, 'y').expect("y coordinate not found (tried 'y', 'yc')");
    let varz = find_coord(&h5, 'z').expect("z coordinate not found (tried 'z', 'zc')");

    // Default blocks: full extent
    let blockx = view_block(&args.block.blockx, sx);
    let blocky = view_block(&args.block.blocky, sy);
    let blockz = view_block(&args.block.blockz, sz);

    // Build per-variable specs (with periodicity detection)
    let var_specs: Vec<VarSpec> = args.variables.iter().filter_map(|var| {
        let shape = h5.dataset(var)?.shape();
        if shape.len() < 3 { return None; }

        // Periodicity: ghost layers add 2 to y and/or x
        let y_per = usize::from(shape[1] == sy + 2);
        let x_per = usize::from(shape[2] == sx + 2);

        let mut vbx = blockx; vbx[0] += x_per;
        let mut vby = blocky; vby[0] += y_per;

        Some(VarSpec {
            name: var.clone(),
            full_shape: [shape[0], shape[1], shape[2]],
            blockz,
            blocky: vby,
            blockx: vbx,
        })
    }).collect();

    // Use absolute path so Paraview can find the HDF5 regardless of working dir
    let hdf5_abs = std::fs::canonicalize(&args.file)
        .map(|p| p.to_string_lossy().into_owned())
        .unwrap_or_else(|_| args.file.clone());

    let output_path = args.output.unwrap_or_else(|| args.file.clone());
    write_xdmf(
        Path::new(&output_path),
        &hdf5_abs,
        &varx, &vary, &varz,
        sx, sy, sz,
        blockx, blocky, blockz,
        &var_specs,
    ).expect("Failed to write XDMF file");
}

// ─── spectra sub-command ──────────────────────────────────────────────────────

fn run_spectra(args: SpectraArgs) {
    let files = snapshot_templates(&args.files, &args.pattern, &args.range);

    let read_coord = |h5: &H5File, name: &str| -> Array1<f64> {
        match h5
            .coord(name)
            .unwrap_or_else(|| panic!("coord '{name}' not found"))
            .read_data::<f64>()
            .unwrap()
        {
            H5Data::Array(a) => a.into_dimensionality::<Ix1>().unwrap(),
            H5Data::Scalar(_) => panic!("coord '{name}' is scalar"),
        }
    };

    // ── coordinates / metadata from the first snapshot ────────────────────────
    let (y, zc, x, nu) = {
        let mut h5 = H5File::new(&files[0]).expect("failed to open first file");
        h5.get_info().expect("failed to read DNS info");
        h5.load_coords().expect("failed to load coordinates");
        let nu = h5.info().nu.expect("'nu' not in HDF5 file");
        (
            read_coord(&h5, "y"),
            read_coord(&h5, "zc"),
            read_coord(&h5, "x"),
            nu,
        )
    };
    let ny = y.len();
    let nxc = x.len();

    // spanwise grid must be uniform (plain FFT, no windowing)
    let dy = y[1] - y[0];
    for j in 1..ny {
        assert!(
            ((y[j] - y[j - 1]) - dy).abs() < 1e-8 * dy,
            "spanwise grid is not uniform at j={j}"
        );
    }
    let ly = dy * ny as f64;

    let (x0, x1) = match &args.xrange {
        Some(v) => (v[0], v[1]),
        None => (0, nxc),
    };
    assert!(x0 < x1 && x1 <= nxc, "invalid --xrange {x0} {x1} (nx = {nxc})");

    // ── accumulate all snapshots ──────────────────────────────────────────────
    let mut spec: Option<SpanwiseSpectrum> = None;

    for path in &files {
        let mut h5 = H5File::new(path).expect("failed to open HDF5 file");
        h5.add_dataset(&args.variable, None)
            .unwrap_or_else(|e| panic!("dataset '{}' in {path}: {e}", args.variable));
        let raw = match h5
            .dataset(&args.variable)
            .unwrap()
            .read_data::<f64>()
            .unwrap()
        {
            H5Data::Array(a) => a,
            H5Data::Scalar(_) => panic!("'{}' is scalar", args.variable),
        };

        // Align the streamwise extent with the x coordinate array:
        //   nxf == nxc      already aligned
        //   nxf == nxc + 1  inst convention: one extra outflow column at the end
        //   nxf == nxc + 2  subavg convention: one ghost column on each side
        let nxf = raw.shape()[2];
        let aligned: ArrayD<f64> = match nxf.checked_sub(nxc) {
            Some(0) => raw,
            Some(1) => raw.slice_axis(Axis(2), (0..nxc).into()).to_owned(),
            Some(2) => raw.slice_axis(Axis(2), (1..nxc + 1).into()).to_owned(),
            _ => panic!("field x extent {nxf} incompatible with x coord length {nxc}"),
        };
        let window = aligned.slice_axis(Axis(2), (x0..x1).into()).to_owned();

        let acc = spec.get_or_insert_with(|| {
            SpanwiseSpectrum::new(window.shape()[0], ny, ly).expect("SpanwiseSpectrum::new")
        });
        acc.accumulate(&window).expect("accumulate failed");
        eprintln!("accumulated {path}");
    }

    let spec = spec.unwrap();
    let nz = zc.len();

    // ── map requested z locations to grid points (deduplicated) ───────────────
    let mut z_indices: Vec<usize> = Vec::new();
    for &zq in &args.zloc {
        let iz = (0..nz)
            .min_by(|&a, &b| {
                (zc[a] - zq).abs().partial_cmp(&(zc[b] - zq).abs()).unwrap()
            })
            .unwrap();
        if !z_indices.contains(&iz) {
            z_indices.push(iz);
        }
    }

    // ── write outputs ─────────────────────────────────────────────────────────
    let stem = args.output.strip_suffix(".dat").unwrap_or(&args.output);
    let ret = 1.0 / nu;

    let (k, e) = spec.energy_spectrum().expect("energy_spectrum");
    let mut cols: HashMap<String, Array1<f64>> = HashMap::new();
    cols.insert("yk".into(), k);
    for &iz in &z_indices {
        cols.insert(
            format!("e{}_{:.3}", args.variable, zc[iz]),
            e.row(iz).to_owned(),
        );
    }
    let spec_path = format!("{stem}_spec.dat");
    write_dat(Path::new(&spec_path), "yk", ret, &cols).expect("failed to write spectrum");
    eprintln!("wrote {spec_path}");

    let (r, rho) = spec.correlation().expect("correlation");
    let mut cols: HashMap<String, Array1<f64>> = HashMap::new();
    cols.insert("ydel".into(), r);
    for &iz in &z_indices {
        cols.insert(
            format!("r{}_{:.3}", args.variable, zc[iz]),
            rho.row(iz).to_owned(),
        );
    }
    let corr_path = format!("{stem}_corr.dat");
    write_dat(Path::new(&corr_path), "ydel", ret, &cols).expect("failed to write correlation");
    eprintln!("wrote {corr_path}");

    eprintln!(
        "ensemble: {} snapshot(s) x {} x-columns = {} y-lines per z",
        files.len(),
        x1 - x0,
        spec.samples()
    );
}

// ─── fik sub-command ──────────────────────────────────────────────────────────

#[derive(Args)]
struct FikArgs {
    /// Input subavg HDF5 file (raw: uu/uw are total second moments).
    #[arg(short, long, value_name = "FILE")]
    file: String,
    /// Output .dat file (default: fik.dat).
    #[arg(short, long, value_name = "FILE", default_value = "fik.dat")]
    output: String,
    /// Half-channel height h (default: 1.0).
    #[arg(long, default_value_t = 1.0)]
    half_height: f64,
    /// Number of ghost cells to strip from each x-boundary (default: 1).
    #[arg(long, default_value_t = 1usize)]
    ghost_x: usize,
    /// Number of (post-ghost-strip) points to drop from the start of the
    /// x-range, e.g. to discard a corrupted lead-in.
    #[arg(long, default_value_t = 0usize)]
    trim_start: usize,
    /// Number of (post-ghost-strip) points to drop from the end of the
    /// x-range, e.g. to discard a corrupted tail.
    #[arg(long, default_value_t = 0usize)]
    trim_end: usize,
    /// Treat streamwise direction as periodic for derivative stencils.
    #[arg(long, default_value_t = false)]
    periodic_x: bool,
    /// Per-plane mode: one decomposition (and one output file `<output>_p<j>.dat`)
    /// per spanwise plane, with the spanwise terms cf_turb_z/cf_conv_z retained.
    #[arg(long, default_value_t = false)]
    per_plane: bool,
    /// Average over the given spanwise plane indices (comma-separated, e.g.
    /// `--planes 2,5`).  Exact by linearity; spanwise terms do NOT cancel for
    /// a subset of planes.  Writes a single output file.
    #[arg(long, value_delimiter = ',')]
    planes: Option<Vec<usize>>,
}

fn run_fik(args: FikArgs) {
    let mut h5 = H5File::new(&args.file).expect("failed to open HDF5 file");
    h5.get_info().expect("failed to read DNS info");
    h5.load_coords().expect("failed to load coordinates");

    let nu   = h5.info().nu.expect("'nu' not in HDF5 file");
    let re_b = 1.0 / nu;

    // Load 3-D fields helper
    let load = |h5: &mut H5File, name: &str| -> ArrayD<f64> {
        h5.add_dataset(name, None)
          .unwrap_or_else(|e| panic!("dataset '{name}': {e}"));
        match h5.dataset(name).unwrap().read_data::<f64>().unwrap() {
            H5Data::Array(a) => a,
            H5Data::Scalar(_) => panic!("'{name}' is scalar"),
        }
    };

    let u_raw  = load(&mut h5, "u");
    let v_raw  = load(&mut h5, "v");
    let w_raw  = load(&mut h5, "w");
    let p_raw  = load(&mut h5, "p");
    let uu_raw = load(&mut h5, "uu");
    let uw_raw = load(&mut h5, "uw");

    // Strip ghost cells along x (axis 2)
    let g = args.ghost_x;
    let nx_ghost = u_raw.shape()[2];
    let strip = |a: ArrayD<f64>| -> ArrayD<f64> {
        a.slice_axis(Axis(2), (g..nx_ghost - g).into()).to_owned()
    };
    let u  = strip(u_raw);
    let v  = strip(v_raw);
    let w  = strip(w_raw);
    let p  = strip(p_raw);
    let uu = strip(uu_raw);
    let uw = strip(uw_raw);

    // Coordinates
    let load_coord = |h5: &mut H5File, name: &str| -> Array1<f64> {
        match h5.coord(name)
            .unwrap_or_else(|| panic!("coord '{name}' not found"))
            .read_data::<f64>().unwrap()
        {
            H5Data::Array(a) => a.into_dimensionality::<Ix1>().unwrap(),
            H5Data::Scalar(_) => panic!("coord '{name}' is scalar"),
        }
    };
    let x_full  = load_coord(&mut h5, "x");
    let zc = load_coord(&mut h5, "zc");

    // Trim a corrupted lead-in / tail from the streamwise range.
    let nx_full = x_full.len();
    let lo = args.trim_start;
    let hi = nx_full - args.trim_end;
    assert!(lo < hi, "trim_start ({lo}) must be < nx - trim_end ({hi})");
    let trim = |a: ArrayD<f64>| -> ArrayD<f64> {
        a.slice_axis(Axis(2), (lo..hi).into()).to_owned()
    };
    let u  = trim(u);
    let v  = trim(v);
    let w  = trim(w);
    let p  = trim(p);
    let uu = trim(uu);
    let uw = trim(uw);
    let x  = x_full.slice(s![lo..hi]).to_owned();

    // Direct C_f from viscous sublayer: 2ν·u(iz=1) / zc[1]
    let iz1 = 1usize;
    // per spanwise plane j
    let cf_direct_plane = |u: &ArrayD<f64>, j: usize| -> Array1<f64> {
        u.slice(s![iz1, j, ..]).mapv(|uv| 2.0 * nu * uv / zc[iz1])
    };
    // spanwise-averaged
    let cf_direct_mean: Array1<f64> = {
        let u_ymean: Array1<f64> = u.slice(s![iz1, .., ..])
            .mean_axis(ndarray::Axis(0))
            .expect("mean over y");
        u_ymean.mapv(|uv| 2.0 * nu * uv / zc[iz1])
    };

    // Write one decomposition (+ direct C_f) to a .dat file
    let write_fik = |fik: &FikDecomposition, cf_direct: Array1<f64>, path: &str| {
        write_fik_dat(fik, cf_direct, &x, re_b, path);
    };

    if args.per_plane || args.planes.is_some() {
        // ── per-plane mode: spanwise terms retained ──────────────────────────
        let uv = trim(strip(load(&mut h5, "uv")));
        let y  = load_coord(&mut h5, "y");
        let decs = fik_decomposition_planes(
            &u, &v, &w, &p, &uu, &uv, &uw,
            &x, &y, &zc,
            re_b, args.half_height, args.periodic_x,
        ).expect("fik_decomposition_planes failed");

        if let Some(planes) = &args.planes {
            // exact subset average over the selected planes
            for &j in planes {
                assert!(j < decs.len(), "plane index {j} out of range (ny={})", decs.len());
            }
            let sel: Vec<&FikDecomposition> = planes.iter().map(|&j| &decs[j]).collect();
            let fik = fik_average(&sel).expect("fik_average failed");
            let mut cf_dir = Array1::<f64>::zeros(x.len());
            for &j in planes {
                cf_dir = cf_dir + &cf_direct_plane(&u, j);
            }
            cf_dir /= planes.len() as f64;
            write_fik(&fik, cf_dir, &args.output);
        } else {
            let stem = args.output.strip_suffix(".dat").unwrap_or(&args.output).to_string();
            for (j, d) in decs.iter().enumerate() {
                write_fik(d, cf_direct_plane(&u, j), &format!("{stem}_p{j}.dat"));
            }
        }
    } else {
        // ── spanwise-averaged mode (default) ─────────────────────────────────
        let fik = fik_decomposition(
            &u, &v, &w, &p, &uu, &uw,
            &x, &zc,
            re_b,
            args.half_height,
            args.periodic_x,
        ).expect("fik_decomposition failed");
        write_fik(&fik, cf_direct_mean, &args.output);
    }
}

// ─── rd sub-command ───────────────────────────────────────────────────────────

#[derive(Args)]
struct RdArgs {
    /// Input subavg HDF5 file (raw: uu/uw are total second moments).
    #[arg(short, long, value_name = "FILE")]
    file: String,
    /// Output .dat file (default: rd.dat).
    #[arg(short, long, value_name = "FILE", default_value = "rd.dat")]
    output: String,
    /// Half-channel height h (default: 1.0).
    #[arg(long, default_value_t = 1.0)]
    half_height: f64,
    /// Reference velocity U_ref of the RD energy frame; C_f = 2τ_w/U_ref².
    /// Default 1.0 = global bulk velocity in DNS units (matches direct C_f).
    #[arg(long, default_value_t = 1.0)]
    u_ref: f64,
    /// Number of ghost cells to strip from each x-boundary (default: 1).
    #[arg(long, default_value_t = 1usize)]
    ghost_x: usize,
    /// Number of (post-ghost-strip) points to drop from the start of the
    /// x-range, e.g. to discard a corrupted lead-in.
    #[arg(long, default_value_t = 0usize)]
    trim_start: usize,
    /// Number of (post-ghost-strip) points to drop from the end of the
    /// x-range, e.g. to discard a corrupted tail.
    #[arg(long, default_value_t = 0usize)]
    trim_end: usize,
    /// Treat streamwise direction as periodic for derivative stencils.
    #[arg(long, default_value_t = false)]
    periodic_x: bool,
}

fn run_rd(args: RdArgs) {
    let mut h5 = H5File::new(&args.file).expect("failed to open HDF5 file");
    h5.get_info().expect("failed to read DNS info");
    h5.load_coords().expect("failed to load coordinates");

    let nu   = h5.info().nu.expect("'nu' not in HDF5 file");
    let re_b = 1.0 / nu;

    let load = |h5: &mut H5File, name: &str| -> ArrayD<f64> {
        h5.add_dataset(name, None)
          .unwrap_or_else(|e| panic!("dataset '{name}': {e}"));
        match h5.dataset(name).unwrap().read_data::<f64>().unwrap() {
            H5Data::Array(a) => a,
            H5Data::Scalar(_) => panic!("'{name}' is scalar"),
        }
    };

    let u_raw  = load(&mut h5, "u");
    let w_raw  = load(&mut h5, "w");
    let p_raw  = load(&mut h5, "p");
    let uu_raw = load(&mut h5, "uu");
    let uw_raw = load(&mut h5, "uw");

    // Strip ghost cells along x (axis 2), then trim a corrupted lead-in/tail.
    let g = args.ghost_x;
    let nx_ghost = u_raw.shape()[2];
    let load_coord = |h5: &mut H5File, name: &str| -> Array1<f64> {
        match h5.coord(name)
            .unwrap_or_else(|| panic!("coord '{name}' not found"))
            .read_data::<f64>().unwrap()
        {
            H5Data::Array(a) => a.into_dimensionality::<Ix1>().unwrap(),
            H5Data::Scalar(_) => panic!("coord '{name}' is scalar"),
        }
    };
    let x_full = load_coord(&mut h5, "x");
    let zc     = load_coord(&mut h5, "zc");

    let nx_full = x_full.len();
    let lo = args.trim_start;
    let hi = nx_full - args.trim_end;
    assert!(lo < hi, "trim_start ({lo}) must be < nx - trim_end ({hi})");

    let cut = |a: ArrayD<f64>| -> ArrayD<f64> {
        let stripped = a.slice_axis(Axis(2), (g..nx_ghost - g).into()).to_owned();
        stripped.slice_axis(Axis(2), (lo..hi).into()).to_owned()
    };
    let u  = cut(u_raw);
    let w  = cut(w_raw);
    let p  = cut(p_raw);
    let uu = cut(uu_raw);
    let uw = cut(uw_raw);
    let x  = x_full.slice(s![lo..hi]).to_owned();

    // Direct C_f from viscous sublayer: 2ν·u(iz=1) / zc[1]
    let iz1 = 1usize;
    let cf_direct: Array1<f64> = {
        let u_ymean: Array1<f64> = u.slice(s![iz1, .., ..])
            .mean_axis(ndarray::Axis(0))
            .expect("mean over y");
        u_ymean.mapv(|uv| 2.0 * nu * uv / zc[iz1])
    };

    let rd = rd_decomposition(
        &u, &w, &p, &uu, &uw,
        &x, &zc,
        re_b,
        args.half_height,
        args.u_ref,
        args.periodic_x,
    ).expect("rd_decomposition failed");

    write_rd_dat(&rd, cf_direct, &x, re_b, &args.output);
}

// ─── shared .dat writers (used by both the subavg and instantaneous paths) ────

/// Write one FIK decomposition (+ direct C_f) to a `.dat` file.
fn write_fik_dat(
    fik: &FikDecomposition,
    cf_direct: Array1<f64>,
    x: &Array1<f64>,
    re_b: f64,
    path: &str,
) {
    let mut cols: HashMap<String, Array1<f64>> = HashMap::new();
    cols.insert("x".into(),         x.clone());
    cols.insert("cf_direct".into(), cf_direct);
    cols.insert("cf_fik".into(),    fik.cf_total());
    cols.insert("cf_lam".into(),    fik.cf_laminar.clone());
    cols.insert("cf_center".into(), fik.cf_center.clone());
    cols.insert("cf_turb_x".into(), fik.cf_turb_x.clone());
    cols.insert("cf_turb_y".into(), fik.cf_turb_y.clone());
    cols.insert("cf_turb_z".into(), fik.cf_turb_z.clone());
    cols.insert("cf_conv_x".into(), fik.cf_conv_x.clone());
    cols.insert("cf_conv_y".into(), fik.cf_conv_y.clone());
    cols.insert("cf_conv_z".into(), fik.cf_conv_z.clone());
    cols.insert("cf_diff_x".into(), fik.cf_diff_x.clone());
    cols.insert("cf_diff_z".into(), fik.cf_diff_z.clone());
    cols.insert("cf_source".into(), fik.cf_source.clone());
    write_dat(Path::new(path), "x", re_b, &cols)
        .expect("failed to write .dat file");
    eprintln!("wrote {path}");
}

/// Write one Renard–Deck decomposition (+ direct C_f) to a `.dat` file.
fn write_rd_dat(
    rd: &RdDecomposition,
    cf_direct: Array1<f64>,
    x: &Array1<f64>,
    re_b: f64,
    path: &str,
) {
    let mut cols: HashMap<String, Array1<f64>> = HashMap::new();
    cols.insert("x".into(),         x.clone());
    cols.insert("cf_direct".into(), cf_direct);
    cols.insert("cf_rd".into(),     rd.cf_total());
    cols.insert("cf_diss".into(),   rd.cf_diss.clone());
    cols.insert("cf_prod".into(),   rd.cf_prod.clone());
    cols.insert("cf_growth".into(), rd.cf_growth());
    cols.insert("cf_conv_x".into(), rd.cf_conv_x.clone());
    cols.insert("cf_conv_y".into(), rd.cf_conv_y.clone());
    cols.insert("cf_turb_x".into(), rd.cf_turb_x.clone());
    cols.insert("cf_diff_x".into(), rd.cf_diff_x.clone());
    cols.insert("cf_source".into(), rd.cf_source.clone());
    cols.insert("cf_center".into(), rd.cf_center.clone());
    write_dat(Path::new(path), "x", re_b, &cols)
        .expect("failed to write .dat file");
    eprintln!("wrote {path}");
}

// ─── shared: instantaneous-snapshot ensemble ──────────────────────────────────

/// Build the full snapshot list from explicit templates plus an optional
/// `--pattern`/`--range` series.  Pattern entries have their `{t}` placeholder
/// replaced by each timestep `START, START+STEP, …, ≤ END`; the component
/// placeholder `{}` is left for [`inst_path`].
fn snapshot_templates(
    files: &[String],
    pattern: &Option<String>,
    range: &Option<Vec<usize>>,
) -> Vec<String> {
    let mut out: Vec<String> = files.to_vec();
    match (pattern, range) {
        (Some(p), Some(r)) => {
            assert!(p.contains("{t}"), "--pattern must contain the time placeholder `{{t}}`");
            let (start, end, step) = (r[0], r[1], r[2]);
            assert!(step > 0, "--range STEP must be > 0");
            assert!(start <= end, "--range START ({start}) must be ≤ END ({end})");
            let mut t = start;
            while t <= end {
                out.push(p.replace("{t}", &t.to_string()));
                t += step;
            }
        }
        (Some(_), None) => panic!("--pattern requires --range START END STEP"),
        (None, Some(_)) => panic!("--range requires --pattern"),
        (None, None) => {}
    }
    assert!(
        !out.is_empty(),
        "no snapshots given; use -f <templates> and/or --pattern + --range"
    );
    out
}

/// Resolve the file that holds component `comp` for a snapshot `template`.
///
/// If the template contains `{}` it is replaced by the component letter
/// (`u`/`v`/`w`/`p`), e.g. `inst_400000_{}.h5` → `inst_400000_u.h5`.  Otherwise
/// every component is read from the same (single-file) snapshot.
fn inst_path(template: &str, comp: char) -> String {
    if template.contains("{}") {
        template.replace("{}", &comp.to_string())
    } else {
        template.to_string()
    }
}

/// Read dataset `name` from `path` and align its streamwise extent to `nxc`,
/// matching the `spectra`/`vortex` convention:
///   nxc      already aligned;
///   nxc + 1  inst files carry one extra outflow column at the end;
///   nxc + 2  subavg files carry one ghost column on each side.
fn read_inst_field(path: &str, name: &str, nxc: usize) -> ArrayD<f64> {
    let mut h5 = H5File::new(path).unwrap_or_else(|e| panic!("open {path}: {e}"));
    h5.add_dataset(name, None)
        .unwrap_or_else(|e| panic!("dataset '{name}' in {path}: {e}"));
    let raw = match h5.dataset(name).unwrap().read_data::<f64>().unwrap() {
        H5Data::Array(a) => a,
        H5Data::Scalar(_) => panic!("'{name}' in {path} is scalar"),
    };
    let nxf = raw.shape()[2];
    match nxf.checked_sub(nxc) {
        Some(0) => raw,
        Some(1) => raw.slice_axis(Axis(2), (0..nxc).into()).to_owned(),
        Some(2) => raw.slice_axis(Axis(2), (1..nxc + 1).into()).to_owned(),
        _ => panic!("field '{name}' x extent {nxf} incompatible with x coord length {nxc}"),
    }
}

/// Span + ensemble statistics assembled from instantaneous snapshots.
///
/// `u`/`v`/`w`/`p` are ensemble means of the primitive fields; `uu`/`uw`/`uv`
/// are ensemble means of the instantaneous *products*.  Feeding these to the
/// existing FIK/RD cores recovers the Reynolds stresses exactly, because those
/// cores form u'u' = ⟨u²⟩ − ū², u'w' = ⟨uw⟩ − ū·w̄ internally (with the
/// remaining spanwise average): identical to computing the fluctuation
/// u' = u − ū first and then u'u'.
struct InstEnsemble {
    u: ArrayD<f64>,
    v: ArrayD<f64>,   // empty ([0]) unless `with_uv`
    w: ArrayD<f64>,
    p: ArrayD<f64>,
    uu: ArrayD<f64>,
    uw: ArrayD<f64>,
    uv: ArrayD<f64>,  // empty ([0]) unless `with_uv`
    x: Array1<f64>,
    y: Array1<f64>,
    zc: Array1<f64>,
    nu: f64,
}

/// Accumulate ensemble means and second moments over the given snapshot
/// templates.  With `with_uv` also accumulates v̄ and ⟨u·v⟩ (needed for the
/// per-plane FIK spanwise terms); otherwise those are left empty to save memory.
fn accumulate_inst(files: &[String], with_uv: bool) -> InstEnsemble {
    assert!(!files.is_empty(), "need at least one snapshot file");

    let read_coord = |h5: &H5File, name: &str| -> Array1<f64> {
        match h5.coord(name)
            .unwrap_or_else(|| panic!("coord '{name}' not found"))
            .read_data::<f64>().unwrap()
        {
            H5Data::Array(a) => a.into_dimensionality::<Ix1>().unwrap(),
            H5Data::Scalar(_) => panic!("coord '{name}' is scalar"),
        }
    };

    // Coordinates / metadata from the first snapshot's u file.
    let (x, y, zc, nu) = {
        let mut h5 = H5File::new(&inst_path(&files[0], 'u'))
            .expect("failed to open first u file");
        h5.get_info().expect("failed to read DNS info");
        h5.load_coords().expect("failed to load coordinates");
        let nu = h5.info().nu.expect("'nu' not in HDF5 file");
        (read_coord(&h5, "x"), read_coord(&h5, "y"), read_coord(&h5, "zc"), nu)
    };
    let nxc = x.len();
    let empty = || ArrayD::<f64>::zeros(ndarray::IxDyn(&[0]));

    // Accumulators: [u, v, w, p, uu, uw, uv].
    let mut acc: Option<[ArrayD<f64>; 7]> = None;
    for f in files {
        let u = read_inst_field(&inst_path(f, 'u'), "u", nxc);
        let w = read_inst_field(&inst_path(f, 'w'), "w", nxc);
        let p = read_inst_field(&inst_path(f, 'p'), "p", nxc);
        let uu = &u * &u;
        let uw = &u * &w;
        let (v, uv) = if with_uv {
            let v = read_inst_field(&inst_path(f, 'v'), "v", nxc);
            let uv = &u * &v;
            (v, uv)
        } else {
            (empty(), empty())
        };

        match &mut acc {
            None => acc = Some([u, v, w, p, uu, uw, uv]),
            Some(a) => {
                a[0] += &u;  a[1] += &v;  a[2] += &w;  a[3] += &p;
                a[4] += &uu; a[5] += &uw; a[6] += &uv;
            }
        }
        eprintln!("accumulated {f}");
    }

    let mut a = acc.unwrap();
    let n = files.len() as f64;
    for arr in a.iter_mut() {
        *arr /= n;
    }
    let [u, v, w, p, uu, uw, uv] = a;
    InstEnsemble { u, v, w, p, uu, uw, uv, x, y, zc, nu }
}

/// Fold the spanwise axis (axis 1) of a `(nz, ny, nx)` field onto `nphase`
/// phase planes by averaging over the spanwise repeats: output plane `p` is the
/// mean of input planes `p, p+nphase, p+2·nphase, …`.  `ny` must be a multiple
/// of `nphase`.
fn fold_spanwise(a: &ArrayD<f64>, nphase: usize) -> ArrayD<f64> {
    let (nz, ny, nx) = (a.shape()[0], a.shape()[1], a.shape()[2]);
    assert!(
        nphase > 0 && ny % nphase == 0,
        "spanwise length {ny} not divisible by nphase {nphase}"
    );
    let mut out = ArrayD::<f64>::zeros(ndarray::IxDyn(&[nz, nphase, nx]));
    for p in 0..nphase {
        let m = a.slice(s![.., p..ny;nphase, ..])
            .mean_axis(Axis(1))
            .expect("mean over spanwise repeats");
        out.slice_mut(s![.., p, ..]).assign(&m);
    }
    out
}

// ─── fik-inst sub-command ─────────────────────────────────────────────────────

#[derive(Args)]
struct FikInstArgs {
    /// Explicit snapshot templates; `{}` is replaced by the component
    /// (u/v/w/p), e.g. `inst_400000_{}.h5`.  All snapshots (these plus any
    /// generated by --pattern/--range) are ensemble-averaged together.  A
    /// template without `{}` is read as a single file holding all components.
    #[arg(short, long, num_args = 1.., value_name = "TEMPLATE")]
    files: Vec<String>,
    /// Filename pattern with a time placeholder `{t}` and component `{}`,
    /// e.g. `inst_{t}_{}.h5`.  Expanded over --range into a snapshot series so
    /// you don't have to list every timestep.
    #[arg(long, value_name = "PATTERN")]
    pattern: Option<String>,
    /// Timestep range START END STEP (inclusive) used with --pattern, e.g.
    /// `--range 400000 900000 50000` for 11 snapshots.
    #[arg(long, num_args = 3, value_names = ["START", "END", "STEP"])]
    range: Option<Vec<usize>>,
    /// Output .dat file (default: fik_inst.dat).
    #[arg(short, long, value_name = "FILE", default_value = "fik_inst.dat")]
    output: String,
    /// Half-channel height h (default: 1.0).
    #[arg(long, default_value_t = 1.0)]
    half_height: f64,
    /// Number of points to drop from the start of the x-range (e.g. a
    /// corrupted inflow lead-in).
    #[arg(long, default_value_t = 0usize)]
    trim_start: usize,
    /// Number of points to drop from the end of the x-range (e.g. a corrupted
    /// outflow tail).
    #[arg(long, default_value_t = 0usize)]
    trim_end: usize,
    /// Treat streamwise direction as periodic for derivative stencils.
    #[arg(long, default_value_t = false)]
    periodic_x: bool,
    /// Per-plane mode: fold the spanwise direction onto the control period and
    /// write one decomposition (file `<output>_p<j>.dat`) per phase plane, with
    /// the spanwise terms cf_turb_z/cf_conv_z retained.
    #[arg(long, default_value_t = false)]
    per_plane: bool,
    /// Average over the given phase-plane indices (comma-separated, 0..nphase).
    #[arg(long, value_delimiter = ',')]
    planes: Option<Vec<usize>>,
    /// Number of spanwise grid points per control period (phase planes).  The
    /// full spanwise extent is folded onto this many phases for per-plane mode;
    /// must divide the spanwise grid size.  Default 1 (fold the whole span onto
    /// a single plane); set to the control period (e.g. 8) to resolve phases.
    #[arg(long, default_value_t = 1usize)]
    nphase: usize,
}

fn run_fik_inst(args: FikInstArgs) {
    // Phase-resolved (per-plane) mode only matters when the span is folded onto
    // more than one phase; with nphase == 1 the whole span is one plane and the
    // spanwise flux terms vanish, so we fall through to the averaged core.
    let with_uv = (args.per_plane || args.planes.is_some()) && args.nphase > 1;
    let files = snapshot_templates(&args.files, &args.pattern, &args.range);
    let ens = accumulate_inst(&files, with_uv);
    let nu = ens.nu;
    let re_b = 1.0 / nu;

    // Trim a corrupted lead-in / tail from the streamwise range.
    let nx_full = ens.x.len();
    let lo = args.trim_start;
    let hi = nx_full - args.trim_end;
    assert!(lo < hi, "trim_start ({lo}) must be < nx - trim_end ({hi})");
    let trim = |a: &ArrayD<f64>| a.slice_axis(Axis(2), (lo..hi).into()).to_owned();

    let u  = trim(&ens.u);
    let w  = trim(&ens.w);
    let p  = trim(&ens.p);
    let uu = trim(&ens.uu);
    let uw = trim(&ens.uw);
    let x  = ens.x.slice(s![lo..hi]).to_owned();
    let zc = ens.zc;

    // Direct C_f from viscous sublayer: 2ν·u(iz=1)/zc[1].
    let iz1 = 1usize;
    let cf_direct_plane = |u: &ArrayD<f64>, j: usize| -> Array1<f64> {
        u.slice(s![iz1, j, ..]).mapv(|uv| 2.0 * nu * uv / zc[iz1])
    };
    let cf_direct_mean: Array1<f64> = {
        let u_ymean: Array1<f64> = u.slice(s![iz1, .., ..])
            .mean_axis(ndarray::Axis(0))
            .expect("mean over y");
        u_ymean.mapv(|uv| 2.0 * nu * uv / zc[iz1])
    };

    if with_uv {
        // ── per-plane mode: fold the spanwise direction onto the control
        // period (`nphase` points per cycle) and decompose each phase plane.
        // Points j, j+nphase, j+2·nphase, … share the same phase, so folding
        // = phase-averaging over the spanwise repeats, matching the subavg
        // convention (which stores exactly `nphase` spanwise phases).
        let np = args.nphase;
        let v  = trim(&ens.v);
        let uv = trim(&ens.uv);
        let uf  = fold_spanwise(&u,  np);
        let vf  = fold_spanwise(&v,  np);
        let wf  = fold_spanwise(&w,  np);
        let pf  = fold_spanwise(&p,  np);
        let uuf = fold_spanwise(&uu, np);
        let uvf = fold_spanwise(&uv, np);
        let uwf = fold_spanwise(&uw, np);
        let y   = ens.y.slice(s![0..np]).to_owned();
        let decs = fik_decomposition_planes(
            &uf, &vf, &wf, &pf, &uuf, &uvf, &uwf,
            &x, &y, &zc,
            re_b, args.half_height, args.periodic_x,
        ).expect("fik_decomposition_planes failed");

        if let Some(planes) = &args.planes {
            for &j in planes {
                assert!(j < decs.len(), "plane index {j} out of range (nphase={})", decs.len());
            }
            let sel: Vec<&FikDecomposition> = planes.iter().map(|&j| &decs[j]).collect();
            let fik = fik_average(&sel).expect("fik_average failed");
            let mut cf_dir = Array1::<f64>::zeros(x.len());
            for &j in planes {
                cf_dir = cf_dir + &cf_direct_plane(&uf, j);
            }
            cf_dir /= planes.len() as f64;
            write_fik_dat(&fik, cf_dir, &x, re_b, &args.output);
        } else {
            let stem = args.output.strip_suffix(".dat").unwrap_or(&args.output).to_string();
            for (j, d) in decs.iter().enumerate() {
                write_fik_dat(d, cf_direct_plane(&uf, j), &x, re_b, &format!("{stem}_p{j}.dat"));
            }
        }
    } else {
        // ── spanwise-averaged mode (default) ─────────────────────────────────
        // v is unused by fik_decomposition (spanwise-homogeneous); pass u as a
        // shape-compatible placeholder.
        let fik = fik_decomposition(
            &u, &u, &w, &p, &uu, &uw,
            &x, &zc,
            re_b, args.half_height, args.periodic_x,
        ).expect("fik_decomposition failed");
        write_fik_dat(&fik, cf_direct_mean, &x, re_b, &args.output);
    }
}

// ─── rd-inst sub-command ──────────────────────────────────────────────────────

#[derive(Args)]
struct RdInstArgs {
    /// Explicit snapshot templates; `{}` is replaced by the component
    /// (u/v/w/p), e.g. `inst_400000_{}.h5`.  Combined with any snapshots
    /// generated by --pattern/--range and all ensemble-averaged together.
    #[arg(short, long, num_args = 1.., value_name = "TEMPLATE")]
    files: Vec<String>,
    /// Filename pattern with a time placeholder `{t}` and component `{}`,
    /// e.g. `inst_{t}_{}.h5`.  Expanded over --range into a snapshot series.
    #[arg(long, value_name = "PATTERN")]
    pattern: Option<String>,
    /// Timestep range START END STEP (inclusive) used with --pattern, e.g.
    /// `--range 400000 900000 50000` for 11 snapshots.
    #[arg(long, num_args = 3, value_names = ["START", "END", "STEP"])]
    range: Option<Vec<usize>>,
    /// Output .dat file (default: rd_inst.dat).
    #[arg(short, long, value_name = "FILE", default_value = "rd_inst.dat")]
    output: String,
    /// Half-channel height h (default: 1.0).
    #[arg(long, default_value_t = 1.0)]
    half_height: f64,
    /// Reference velocity U_ref of the RD energy frame; C_f = 2τ_w/U_ref².
    #[arg(long, default_value_t = 1.0)]
    u_ref: f64,
    /// Number of points to drop from the start of the x-range.
    #[arg(long, default_value_t = 0usize)]
    trim_start: usize,
    /// Number of points to drop from the end of the x-range.
    #[arg(long, default_value_t = 0usize)]
    trim_end: usize,
    /// Treat streamwise direction as periodic for derivative stencils.
    #[arg(long, default_value_t = false)]
    periodic_x: bool,
}

fn run_rd_inst(args: RdInstArgs) {
    let files = snapshot_templates(&args.files, &args.pattern, &args.range);
    let ens = accumulate_inst(&files, false);
    let nu = ens.nu;
    let re_b = 1.0 / nu;

    let nx_full = ens.x.len();
    let lo = args.trim_start;
    let hi = nx_full - args.trim_end;
    assert!(lo < hi, "trim_start ({lo}) must be < nx - trim_end ({hi})");
    let trim = |a: &ArrayD<f64>| a.slice_axis(Axis(2), (lo..hi).into()).to_owned();

    let u  = trim(&ens.u);
    let w  = trim(&ens.w);
    let p  = trim(&ens.p);
    let uu = trim(&ens.uu);
    let uw = trim(&ens.uw);
    let x  = ens.x.slice(s![lo..hi]).to_owned();
    let zc = ens.zc;

    let iz1 = 1usize;
    let cf_direct: Array1<f64> = {
        let u_ymean: Array1<f64> = u.slice(s![iz1, .., ..])
            .mean_axis(ndarray::Axis(0))
            .expect("mean over y");
        u_ymean.mapv(|uv| 2.0 * nu * uv / zc[iz1])
    };

    let rd = rd_decomposition(
        &u, &w, &p, &uu, &uw,
        &x, &zc,
        re_b, args.half_height, args.u_ref, args.periodic_x,
    ).expect("rd_decomposition failed");

    write_rd_dat(&rd, cf_direct, &x, re_b, &args.output);
}

// ─── tke sub-commands ─────────────────────────────────────────────────────────

#[derive(Args)]
struct TkeArgs {
    /// Input subavg HDF5 file (raw: uu/vv/ww/uv/uw/vw are total second moments).
    #[arg(short, long, value_name = "FILE")]
    file: String,
    /// Output .dat file (default: tke.dat).  With --xloc, one file
    /// `<output stem>_x<pos>.dat` per station instead.
    #[arg(short, long, value_name = "FILE", default_value = "tke.dat")]
    output: String,
    /// Physical x locations for wall-normal profiles, comma-separated; each is
    /// snapped to the nearest grid point and written to its own file.
    #[arg(long, value_delimiter = ',')]
    xloc: Option<Vec<f64>>,
    /// x-index range START END (0-based, half-open) to average the profiles
    /// over when --xloc is not given; default: full streamwise extent.
    #[arg(long, num_args = 2, value_name = "INT")]
    xrange: Option<Vec<usize>>,
}

fn run_tke(args: TkeArgs) {
    let mut h5 = H5File::new(&args.file).expect("failed to open HDF5 file");
    h5.get_info().expect("failed to read DNS info");
    h5.load_coords().expect("failed to load coordinates");
    let nu = h5.info().nu.expect("'nu' not in HDF5 file");

    let load_coord = |h5: &H5File, name: &str| -> Array1<f64> {
        match h5.coord(name)
            .unwrap_or_else(|| panic!("coord '{name}' not found"))
            .read_data::<f64>().unwrap()
        {
            H5Data::Array(a) => a.into_dimensionality::<Ix1>().unwrap(),
            H5Data::Scalar(_) => panic!("coord '{name}' is scalar"),
        }
    };
    let x  = load_coord(&h5, "x");
    let zc = load_coord(&h5, "zc");
    let nxc = x.len();
    drop(h5);

    // read_inst_field's alignment also covers the subavg ghost convention
    // (nx + 2 → strip one column each side).
    let load = |name: &str| read_inst_field(&args.file, name, nxc);
    let u  = load("u");
    let v  = load("v");
    let w  = load("w");
    let uu = load("uu");
    let vv = load("vv");
    let ww = load("ww");
    let uv = load("uv");
    let uw = load("uw");
    let vw = load("vw");

    let tf = tke_fields(&u, &v, &w, &uu, &vv, &ww, &uv, &uw, &vw)
        .expect("tke_fields failed");
    write_tke_outputs(&tf, &x, &zc, 1.0 / nu, &args.xloc, &args.xrange, &args.output);
}

#[derive(Args)]
struct TkeInstArgs {
    /// Explicit snapshot templates; `{}` is replaced by the component
    /// (u/v/w), e.g. `inst_400000_{}.h5`.  Combined with any snapshots
    /// generated by --pattern/--range and all ensemble-averaged together.
    #[arg(short, long, num_args = 1.., value_name = "TEMPLATE")]
    files: Vec<String>,
    /// Filename pattern with a time placeholder `{t}` and component `{}`,
    /// e.g. `inst_{t}_{}.h5`.  Expanded over --range into a snapshot series.
    #[arg(long, value_name = "PATTERN")]
    pattern: Option<String>,
    /// Timestep range START END STEP (inclusive) used with --pattern.
    #[arg(long, num_args = 3, value_names = ["START", "END", "STEP"])]
    range: Option<Vec<usize>>,
    /// Output .dat file (default: tke_inst.dat).  With --xloc, one file
    /// `<output stem>_x<pos>.dat` per station instead.
    #[arg(short, long, value_name = "FILE", default_value = "tke_inst.dat")]
    output: String,
    /// Physical x locations for wall-normal profiles, comma-separated; each is
    /// snapped to the nearest grid point and written to its own file.
    #[arg(long, value_delimiter = ',')]
    xloc: Option<Vec<f64>>,
    /// x-index range START END (0-based, half-open) to average the profiles
    /// over when --xloc is not given; default: full streamwise extent.
    #[arg(long, num_args = 2, value_name = "INT")]
    xrange: Option<Vec<usize>>,
}

fn run_tke_inst(args: TkeInstArgs) {
    let files = snapshot_templates(&args.files, &args.pattern, &args.range);
    let ens = accumulate_inst_tke(&files);
    let tf = tke_fields(
        &ens.u, &ens.v, &ens.w,
        &ens.uu, &ens.vv, &ens.ww,
        &ens.uv, &ens.uw, &ens.vw,
    ).expect("tke_fields failed");
    write_tke_outputs(
        &tf, &ens.x, &ens.zc, 1.0 / ens.nu,
        &args.xloc, &args.xrange, &args.output,
    );
}

/// Ensemble means for the TKE path: primitive means ū/v̄/w̄ and all six total
/// second moments ⟨uu⟩…⟨vw⟩, streamed one snapshot at a time.
struct TkeEnsemble {
    u: ArrayD<f64>,
    v: ArrayD<f64>,
    w: ArrayD<f64>,
    uu: ArrayD<f64>,
    vv: ArrayD<f64>,
    ww: ArrayD<f64>,
    uv: ArrayD<f64>,
    uw: ArrayD<f64>,
    vw: ArrayD<f64>,
    x: Array1<f64>,
    zc: Array1<f64>,
    nu: f64,
}

fn accumulate_inst_tke(files: &[String]) -> TkeEnsemble {
    assert!(!files.is_empty(), "need at least one snapshot file");

    let read_coord = |h5: &H5File, name: &str| -> Array1<f64> {
        match h5.coord(name)
            .unwrap_or_else(|| panic!("coord '{name}' not found"))
            .read_data::<f64>().unwrap()
        {
            H5Data::Array(a) => a.into_dimensionality::<Ix1>().unwrap(),
            H5Data::Scalar(_) => panic!("coord '{name}' is scalar"),
        }
    };
    let (x, zc, nu) = {
        let mut h5 = H5File::new(&inst_path(&files[0], 'u'))
            .expect("failed to open first u file");
        h5.get_info().expect("failed to read DNS info");
        h5.load_coords().expect("failed to load coordinates");
        let nu = h5.info().nu.expect("'nu' not in HDF5 file");
        (read_coord(&h5, "x"), read_coord(&h5, "zc"), nu)
    };
    let nxc = x.len();

    // Accumulators: [u, v, w, uu, vv, ww, uv, uw, vw].
    let mut acc: Option<[ArrayD<f64>; 9]> = None;
    for f in files {
        let u = read_inst_field(&inst_path(f, 'u'), "u", nxc);
        let v = read_inst_field(&inst_path(f, 'v'), "v", nxc);
        let w = read_inst_field(&inst_path(f, 'w'), "w", nxc);
        match &mut acc {
            None => {
                let (uu, vv, ww) = (&u * &u, &v * &v, &w * &w);
                let (uv, uw, vw) = (&u * &v, &u * &w, &v * &w);
                acc = Some([u, v, w, uu, vv, ww, uv, uw, vw]);
            }
            Some(a) => {
                a[3] += &(&u * &u);
                a[4] += &(&v * &v);
                a[5] += &(&w * &w);
                a[6] += &(&u * &v);
                a[7] += &(&u * &w);
                a[8] += &(&v * &w);
                a[0] += &u;
                a[1] += &v;
                a[2] += &w;
            }
        }
        eprintln!("accumulated {f}");
    }

    let mut a = acc.unwrap();
    let n = files.len() as f64;
    for arr in a.iter_mut() {
        *arr /= n;
    }
    let [u, v, w, uu, vv, ww, uv, uw, vw] = a;
    TkeEnsemble { u, v, w, uu, vv, ww, uv, uw, vw, x, zc, nu }
}

/// Write Reynolds-stress/TKE wall-normal profiles to .dat file(s).
///
/// With `xloc`: one file `<stem>_x<pos>.dat` per station (nearest grid point).
/// Otherwise a single file with profiles averaged over `xrange`
/// (default: the full streamwise extent).
fn write_tke_outputs(
    tf: &TkeFields,
    x:  &Array1<f64>,
    zc: &Array1<f64>,
    ret: f64,
    xloc: &Option<Vec<f64>>,
    xrange: &Option<Vec<usize>>,
    output: &str,
) {
    let nx = x.len();
    let fields: [(&str, &ArrayD<f64>); 7] = [
        ("uu", &tf.uu), ("vv", &tf.vv), ("ww", &tf.ww),
        ("uv", &tf.uv), ("uw", &tf.uw), ("vw", &tf.vw),
        ("tke", &tf.tke),
    ];
    let write = |profile: &dyn Fn(&ArrayD<f64>) -> Array1<f64>, path: &str| {
        let mut cols: HashMap<String, Array1<f64>> = HashMap::new();
        cols.insert("zc".into(), zc.clone());
        for (name, f) in &fields {
            cols.insert((*name).into(), profile(f));
        }
        write_dat(Path::new(path), "zc", ret, &cols)
            .expect("failed to write .dat file");
        eprintln!("wrote {path}");
    };

    match xloc {
        Some(locs) => {
            let stem = output.strip_suffix(".dat").unwrap_or(output).to_string();
            for &xq in locs {
                let ix = (0..nx)
                    .min_by(|&a, &b| {
                        (x[a] - xq).abs().partial_cmp(&(x[b] - xq).abs()).unwrap()
                    })
                    .unwrap();
                let station = |f: &ArrayD<f64>| -> Array1<f64> {
                    f.slice(s![.., ix]).to_owned()
                        .into_dimensionality::<Ix1>().unwrap()
                };
                write(&station, &format!("{stem}_x{:.2}.dat", x[ix]));
            }
        }
        None => {
            let (i0, i1) = match xrange {
                Some(v) => (v[0], v[1]),
                None => (0, nx),
            };
            assert!(i0 < i1 && i1 <= nx, "invalid --xrange {i0} {i1} (nx = {nx})");
            let xmean = |f: &ArrayD<f64>| -> Array1<f64> {
                f.slice_axis(Axis(1), (i0..i1).into())
                    .mean_axis(Axis(1)).expect("mean over x")
                    .into_dimensionality::<Ix1>().unwrap()
            };
            write(&xmean, output);
        }
    }
}

// ─── vortex sub-command ───────────────────────────────────────────────────────

#[derive(Args)]
struct VortexArgs {
    /// Instantaneous snapshot HDF5 file containing dataset `u` (streamwise).
    #[arg(short = 'u', long, value_name = "FILE")]
    ufile: String,
    /// Snapshot file containing dataset `v` (spanwise); default: same as --ufile.
    #[arg(short = 'v', long, value_name = "FILE")]
    vfile: Option<String>,
    /// Snapshot file containing dataset `w` (wall-normal); default: same as --ufile.
    #[arg(short = 'w', long, value_name = "FILE")]
    wfile: Option<String>,
    /// Output HDF5 file with q/lambda2/u fields (+ x/y/zc/nu).
    #[arg(short, long, value_name = "FILE", default_value = "vortex.h5")]
    output: String,
    /// Treat streamwise direction as periodic for derivative stencils.
    #[arg(long, default_value_t = false)]
    periodic_x: bool,
}

fn run_vortex(args: VortexArgs) {
    // ── coordinates / metadata from the u file ───────────────────────────────
    let mut h5u = H5File::new(&args.ufile).expect("failed to open u file");
    h5u.get_info().expect("failed to read DNS info");
    h5u.load_coords().expect("failed to load coordinates");

    let read_coord = |h5: &H5File, name: &str| -> Array1<f64> {
        match h5
            .coord(name)
            .unwrap_or_else(|| panic!("coord '{name}' not found"))
            .read_data::<f64>()
            .unwrap()
        {
            H5Data::Array(a) => a.into_dimensionality::<Ix1>().unwrap(),
            H5Data::Scalar(_) => panic!("coord '{name}' is scalar"),
        }
    };
    let x = read_coord(&h5u, "x");
    let y = read_coord(&h5u, "y");
    let zc = read_coord(&h5u, "zc");
    let nu = h5u.info().nu.expect("'nu' not in HDF5 file");
    let (nxc, ny, nz) = (x.len(), y.len(), zc.len());
    drop(h5u);

    // Align the field's streamwise extent with the x coordinate array
    // (same conventions as the spectra sub-command).
    let align = |raw: ArrayD<f64>| -> ArrayD<f64> {
        let nxf = raw.shape()[2];
        match nxf.checked_sub(nxc) {
            Some(0) => raw,
            Some(1) => raw.slice_axis(Axis(2), (0..nxc).into()).to_owned(),
            Some(2) => raw.slice_axis(Axis(2), (1..nxc + 1).into()).to_owned(),
            _ => panic!("field x extent {nxf} incompatible with x coord length {nxc}"),
        }
    };
    let load_field = |path: &str, name: &str| -> ArrayD<f64> {
        let mut h5 = H5File::new(path).expect("failed to open HDF5 file");
        h5.add_dataset(name, None)
            .unwrap_or_else(|e| panic!("dataset '{name}' in {path}: {e}"));
        let raw = match h5.dataset(name).unwrap().read_data::<f64>().unwrap() {
            H5Data::Array(a) => a,
            H5Data::Scalar(_) => panic!("'{name}' is scalar"),
        };
        align(raw)
    };

    let u = load_field(&args.ufile, "u");
    let v = load_field(args.vfile.as_deref().unwrap_or(&args.ufile), "v");
    let w = load_field(args.wfile.as_deref().unwrap_or(&args.ufile), "w");
    eprintln!("fields loaded: ({nz}, {ny}, {nxc})");

    // ── Q and λ₂ ──────────────────────────────────────────────────────────────
    let vf = vortex_criteria(&u, &v, &w, &x, &y, &zc, [false, true, args.periodic_x])
        .expect("vortex_criteria failed");
    drop(v);
    drop(w);
    eprintln!("Q and λ₂ computed");

    // ── isosurface-level guidance: tail quantiles ─────────────────────────────
    let quantiles = |field: &ArrayD<f64>, fractions: &[f64], lower_tail: bool| -> Vec<f64> {
        let mut sample: Vec<f64> = field.as_slice().unwrap().iter().step_by(16).copied().collect();
        sample.sort_by(|a, b| a.partial_cmp(b).unwrap());
        fractions
            .iter()
            .map(|&f| {
                let frac = if lower_tail { f } else { 1.0 - f };
                sample[((sample.len() - 1) as f64 * frac) as usize]
            })
            .collect()
    };
    let fr = [0.001, 0.005, 0.01, 0.02, 0.05];
    let l2q = quantiles(&vf.lambda2, &fr, true);
    let qq = quantiles(&vf.q, &fr, false);
    eprintln!("suggested isosurface levels (tail quantiles of the sampled field):");
    for (i, f) in fr.iter().enumerate() {
        eprintln!(
            "  {:>5.1}%:  lambda2 = {:>12.4e}    q = {:>12.4e}",
            f * 100.0,
            l2q[i],
            qq[i]
        );
    }

    // ── write HDF5 (q, lambda2, u + coords/metadata) ──────────────────────────
    let out = hdf5::File::create(&args.output).expect("failed to create output HDF5");
    let write3d = |name: &str, a: &ArrayD<f64>| {
        out.new_dataset_builder()
            .with_data(a.view())
            .create(name)
            .unwrap_or_else(|e| panic!("write '{name}': {e}"));
    };
    write3d("q", &vf.q);
    write3d("lambda2", &vf.lambda2);
    write3d("u", &u);
    let write1d = |name: &str, a: &Array1<f64>| {
        out.new_dataset_builder()
            .with_data(a.view())
            .create(name)
            .unwrap_or_else(|e| panic!("write '{name}': {e}"));
    };
    write1d("x", &x);
    write1d("y", &y);
    write1d("zc", &zc);
    write1d("nu", &Array1::from_elem(1, nu));
    drop(out);
    eprintln!("wrote {}", args.output);
    eprintln!(
        "to view in Paraview, generate an XDMF for the region of interest, e.g.:\n  \
         datapostproc-rust hdfview -f {} -v q lambda2 u",
        args.output
    );
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

fn dire_to_axis(dire: &str) -> usize {
    match dire.to_lowercase().as_str() {
        "z" => 0,
        "y" => 1,
        "x" => 2,
        d   => panic!("Unknown direction '{}' – expected x, y, or z", d),
    }
}

fn build_block(args: &BlockArgs) -> Option<Block> {
    if args.blockx.is_none() && args.blocky.is_none() && args.blockz.is_none() {
        return None;
    }
    let bv = |v: &Vec<usize>| BlockValue::new([v[0], v[1], v[2], v[3]]).expect("invalid block");
    let bz = args.blockz.as_ref().map(bv);
    let by = args.blocky.as_ref().map(bv);
    let bx = args.blockx.as_ref().map(bv);
    Some(Block::new(vec![bz, by, bx]))
}

/// Default [start, stride, count] = [0, 1, full_extent].
fn view_block(arg: &Option<Vec<usize>>, full: usize) -> [usize; 3] {
    match arg {
        Some(v) => [v[0], v[1], v[2]],
        None    => [0, 1, full],
    }
}

fn find_coord(h5: &H5File, axis: char) -> Option<String> {
    let plain = axis.to_string();
    if h5.coord(&plain).is_some() { return Some(plain); }
    let with_c = format!("{}c", axis);
    if h5.coord(&with_c).is_some() { return Some(with_c); }
    None
}
